#!/bin/bash

git stash -q --keep-index

echo "Running golangci-lint on staged Go files..."

STAGED_GO_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.go$')

if [ -z "$STAGED_GO_FILES" ]; then
    echo "No staged Go files to lint. Skipping golangci-lint."
    git stash pop -q --index 2>/dev/null
    exit 0
fi

/Users/yuliya_shuleika/go/bin/golangci-lint run --new-from-rev HEAD --fix $STAGED_GO_FILES

LINTER_RESULT=$?

git stash pop -q --index 2>/dev/null

if [ $LINTER_RESULT -ne 0 ]; then
    echo ""
    echo "🚨 golangci-lint found issues. Please fix them before committing."
    exit 1
fi

echo "✅ golangci-lint passed."
exit 0