version: '3.8'

services:
  backend:
    build: ./go-server
    ports:
      - "8080:8080"
    # volumes:
    #   - ./go-server:/app
    networks:
      - app-network

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
